version: "3.9"

services:
  bot:
    build:
      dockerfile: Dockerfile
    container_name: jamination_bot
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@db:5432/sapphire
      DB_URL: postgres://postgres:postgres@db:5432/sapphire
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      OWNERS: ${OWNERS}
    # Optional if you want live logs
    tty: true
    stdin_open: true

  db:
    image: postgres:16
    container_name: sapphire_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sapphire
    ports:
      - "5432:5432"
    volumes:
      - sapphire_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  sapphire_data:

