version: '3.9'

services:
  db:
    image: postgres:16
    container_name: sapphire_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sapphire
    ports:
      - "5432:5432"
    volumes:
      - sapphire_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  sapphire_data:

